# Copyright (c) 2026 Liquid Releasing. Licensed under the MIT License.
# Written by human and Claude AI (Claude Sonnet).

"""Automated accessibility tests for WCAG 2.1 AA fixes.

These tests run without a live Streamlit server.  They check:

  C1 — Audio player HTML attributes (aria-label, role, aria-live)
  C2 — Rejected-row sr-only marker generated by export_panel helpers
  C3 — BPM timeline bar-text logic (numeric labels, threshold, format)
  M1 — No remaining label_visibility="collapsed" in panel source files
  M2 — st.caption() called after the key Plotly charts in assessment.py
  M5 — lang injection present in app.py JS block
"""

import os
import re
import sys
import types
import unittest
from html.parser import HTMLParser
from unittest.mock import MagicMock, patch, call

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_PANELS_DIR = os.path.join(_ROOT, "ui", "streamlit", "panels")
_APP_PY = os.path.join(_ROOT, "ui", "streamlit", "app.py")
_AUDIO_HTML = os.path.join(
    _ROOT, "ui", "streamlit", "components", "audio_player", "frontend", "index.html"
)
_ASSESSMENT_PY = os.path.join(_PANELS_DIR, "assessment.py")
_EXPORT_PY = os.path.join(_PANELS_DIR, "export_panel.py")


# ===========================================================================
# C1 — Audio player HTML: aria-label, role, aria-live
# ===========================================================================

class _ButtonCollector(HTMLParser):
    """Collect button tags and their attributes."""
    def __init__(self):
        super().__init__()
        self.buttons = []          # list of attr dicts
        self.spans   = []          # list of (id, attr dict)

    def handle_starttag(self, tag, attrs):
        d = dict(attrs)
        if tag == "button":
            self.buttons.append(d)
        elif tag == "span":
            self.spans.append(d)


class TestAudioPlayerAccessibility(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        with open(_AUDIO_HTML, encoding="utf-8") as f:
            cls.html = f.read()
        p = _ButtonCollector()
        p.feed(cls.html)
        cls.buttons = p.buttons
        cls.spans   = p.spans

    # -- Buttons ---------------------------------------------------------------

    def test_all_buttons_have_aria_label(self):
        """Every <button> must have a non-empty aria-label."""
        for btn in self.buttons:
            self.assertIn(
                "aria-label", btn,
                f"Button missing aria-label: {btn}",
            )
            self.assertTrue(btn["aria-label"].strip(), f"Empty aria-label on {btn}")

    def test_back_button_aria_label(self):
        back = next((b for b in self.buttons if b.get("id") == "btn-back"), None)
        self.assertIsNotNone(back, "btn-back not found")
        self.assertIn("1", back["aria-label"].lower())

    def test_forward_button_aria_label(self):
        fwd = next((b for b in self.buttons if b.get("id") == "btn-fwd"), None)
        self.assertIsNotNone(fwd, "btn-fwd not found")
        self.assertIn("1", fwd["aria-label"].lower())

    def test_stop_button_aria_label(self):
        stop = next((b for b in self.buttons if b.get("id") == "btn-stop"), None)
        self.assertIsNotNone(stop)
        self.assertEqual(stop["aria-label"].lower(), "stop")

    def test_pin_button_aria_label(self):
        pin = next((b for b in self.buttons if b.get("id") == "btn-pin"), None)
        self.assertIsNotNone(pin)
        self.assertIn("split", pin["aria-label"].lower())

    def test_play_button_initial_aria_label_is_play(self):
        play = next((b for b in self.buttons if b.get("id") == "btn-play"), None)
        self.assertIsNotNone(play)
        self.assertEqual(play["aria-label"].lower(), "play")

    # -- Time display span -----------------------------------------------------

    def test_time_display_has_role_timer(self):
        td = next((s for s in self.spans if s.get("id") == "time-display"), None)
        self.assertIsNotNone(td, "time-display span not found")
        self.assertEqual(td.get("role"), "timer")

    def test_time_display_has_aria_live(self):
        td = next((s for s in self.spans if s.get("id") == "time-display"), None)
        self.assertIsNotNone(td)
        self.assertIn("aria-live", td)

    # -- Pin label (live region) -----------------------------------------------

    def test_pin_label_has_aria_live_polite(self):
        pl = next((s for s in self.spans if s.get("id") == "pin-label"), None)
        self.assertIsNotNone(pl, "pin-label span not found")
        self.assertEqual(pl.get("aria-live"), "polite")

    # -- Play/pause aria-label updated in JS -----------------------------------

    def test_js_updates_aria_label_on_play(self):
        """JS must call setAttribute('aria-label', 'Pause') when starting playback."""
        self.assertIn(
            "setAttribute(\"aria-label\", \"Pause\")", self.html,
            "JS does not update aria-label to 'Pause' on play",
        )

    def test_js_updates_aria_label_on_pause(self):
        self.assertIn(
            "setAttribute(\"aria-label\", \"Play\")", self.html,
            "JS does not update aria-label back to 'Play' on pause/stop",
        )

    def test_js_aria_label_updated_on_stop(self):
        """Stop handler and end-of-phrase handler must both reset aria-label."""
        count = self.html.count("setAttribute(\"aria-label\", \"Play\")")
        self.assertGreaterEqual(count, 3, "Expected ≥3 aria-label='Play' resets (stop, end-boundary, onRender)")


# ===========================================================================
# C2 — Rejected rows: sr-only marker
# ===========================================================================

class TestRejectedRowSrOnly(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        with open(_EXPORT_PY, encoding="utf-8") as f:
            cls.src = f.read()

    def test_sr_only_span_present_for_rejected_rows(self):
        """export_panel.py must include sr-only markup for rejected rows."""
        self.assertIn(
            "sr-only", self.src,
            "No sr-only span found in export_panel.py — rejected rows not accessible",
        )

    def test_sr_only_contains_rejected_text(self):
        """The sr-only span must communicate 'Rejected' to screen readers."""
        match = re.search(r"sr-only[^>]*>[^<]*Rejected", self.src)
        self.assertIsNotNone(match, "sr-only span does not contain 'Rejected' text")

    def test_sr_only_span_appears_twice(self):
        """Both the completed and recommended tables must have the marker."""
        count = self.src.count("sr-only")
        self.assertGreaterEqual(count, 2, "Expected sr-only in both completed and recommended tables")


# ===========================================================================
# C3 — BPM bar-text logic
# ===========================================================================

def _bar_texts(phrases, bar_widths):
    """Mirror of the bar_texts computation in assessment._render_phrases_timeline."""
    total_dur = sum(bar_widths) or 1
    return [
        f"{ph.get('bpm', 0):.0f}" if (w / total_dur) > 0.04 else ""
        for ph, w in zip(phrases, bar_widths)
    ]


class TestBpmBarTextLogic(unittest.TestCase):

    def _ph(self, bpm):
        return {"bpm": bpm}

    def test_wide_bar_shows_label(self):
        """A bar wider than 4% of total should show a BPM number."""
        phrases    = [self._ph(120)]
        widths     = [1000]
        labels     = _bar_texts(phrases, widths)
        self.assertEqual(labels[0], "120")

    def test_narrow_bar_suppressed(self):
        """A bar ≤ 4% of total width should have an empty label."""
        # 1 narrow bar + 1 very wide bar; narrow is < 4%
        phrases = [self._ph(80), self._ph(120)]
        widths  = [30, 970]          # 30/1000 = 3% → suppressed
        labels  = _bar_texts(phrases, widths)
        self.assertEqual(labels[0], "", "Narrow bar should not have a label")
        self.assertEqual(labels[1], "120")

    def test_exactly_4pct_shows_label(self):
        """A bar at exactly 4.01% should show a label."""
        phrases = [self._ph(95), self._ph(95)]
        widths  = [401, 9599]        # 401/10000 = 4.01%
        labels  = _bar_texts(phrases, widths)
        self.assertEqual(labels[0], "95")

    def test_exactly_at_threshold_suppressed(self):
        """A bar at exactly 4% (not >4%) should be suppressed."""
        phrases = [self._ph(95), self._ph(95)]
        widths  = [400, 9600]        # 400/10000 = 4.00% → not > 0.04
        labels  = _bar_texts(phrases, widths)
        self.assertEqual(labels[0], "")

    def test_label_format_integer(self):
        """BPM label must be a rounded integer string (no decimal)."""
        phrases = [self._ph(123.6)]
        widths  = [1000]
        labels  = _bar_texts(phrases, widths)
        self.assertNotIn(".", labels[0])
        self.assertEqual(labels[0], "124")

    def test_all_equal_width_bars_all_shown(self):
        """When bars are equal width and there are <= 25, all should be shown."""
        phrases = [self._ph(100 + i) for i in range(5)]
        widths  = [200] * 5          # each = 20% → all > 4%
        labels  = _bar_texts(phrases, widths)
        self.assertTrue(all(lbl != "" for lbl in labels))

    def test_empty_phrases_no_error(self):
        labels = _bar_texts([], [])
        self.assertEqual(labels, [])

    def test_single_bar_always_shown(self):
        """A single bar is 100% of total — must always show label."""
        phrases = [self._ph(85)]
        widths  = [5000]
        labels  = _bar_texts(phrases, widths)
        self.assertEqual(labels[0], "85")


# ===========================================================================
# M1 — No label_visibility="collapsed" remaining in panel source files
# ===========================================================================

class TestNoCollapsedLabels(unittest.TestCase):
    """Assert that label_visibility="collapsed" has been removed from panels."""

    def _panel_files(self):
        return [
            os.path.join(_PANELS_DIR, f)
            for f in os.listdir(_PANELS_DIR)
            if f.endswith(".py")
        ]

    def test_no_collapsed_label_visibility_in_panels(self):
        """No panel should suppress labels from the accessibility tree."""
        violations = []
        for path in self._panel_files():
            with open(path, encoding="utf-8") as f:
                src = f.read()
            matches = list(re.finditer(r'label_visibility\s*=\s*["\']collapsed["\']', src))
            for m in matches:
                lineno = src[:m.start()].count("\n") + 1
                violations.append(f"{os.path.basename(path)}:{lineno}")

        self.assertEqual(
            violations, [],
            f"label_visibility='collapsed' found in:\n  " + "\n  ".join(violations),
        )


# ===========================================================================
# M2 — Key charts followed by st.caption() in assessment.py
# ===========================================================================

class TestChartCaptions(unittest.TestCase):
    """Check that each significant Plotly chart in assessment.py is followed
    by an st.caption() call within a short window of source lines."""

    @classmethod
    def setUpClass(cls):
        with open(_ASSESSMENT_PY, encoding="utf-8") as f:
            cls.lines = f.readlines()

    def _caption_follows_chart(self, chart_lineno: int, window: int = 8) -> bool:
        """Return True if st.caption() appears within *window* lines after the chart."""
        for i in range(chart_lineno, min(chart_lineno + window, len(self.lines))):
            if "st.caption(" in self.lines[i]:
                return True
        return False

    def _find_plotly_lines(self):
        return [
            i for i, line in enumerate(self.lines)
            if "st.plotly_chart(" in line
        ]

    def test_phrase_timeline_has_caption(self):
        """_render_phrases_timeline: caption describes colour meaning."""
        src = "".join(self.lines)
        # The timeline caption already existed; verify it's still there.
        self.assertIn(
            "Colour", src,
            "Phrase timeline caption should describe colour meaning",
        )

    def test_bpm_step_chart_has_caption(self):
        """_render_bpm_step_chart: caption describes transitions."""
        src = "".join(self.lines)
        self.assertIn(
            "BPM step chart", src,
            "BPM step chart should have an accessible caption",
        )

    def test_behavioral_tag_chart_has_caption(self):
        """_render_patterns_section bar chart: caption describes content."""
        src = "".join(self.lines)
        self.assertIn(
            "Behavioral tag frequency", src,
            "Behavioral tag chart should have an accessible caption",
        )

    def test_all_plotly_charts_followed_by_caption(self):
        """Every st.plotly_chart() call in assessment.py must be followed
        by an st.caption() within 8 lines."""
        chart_lines = self._find_plotly_lines()
        self.assertGreater(len(chart_lines), 0, "No plotly charts found in assessment.py")

        missing = []
        for lineno in chart_lines:
            if not self._caption_follows_chart(lineno):
                missing.append(lineno + 1)   # 1-based for error messages

        self.assertEqual(
            missing, [],
            f"Charts at lines {missing} in assessment.py have no caption within 8 lines",
        )


# ===========================================================================
# M5 — lang="en" JS injection in app.py
# ===========================================================================

class TestLangInjection(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        with open(_APP_PY, encoding="utf-8") as f:
            cls.src = f.read()

    def test_lang_injection_present(self):
        """app.py must inject lang='en' onto the document element."""
        self.assertIn(
            "documentElement.lang", self.src,
            "Missing lang='en' JS injection in app.py",
        )

    def test_lang_value_is_en(self):
        match = re.search(r"documentElement\.lang\s*=\s*['\"](\w+)['\"]", self.src)
        self.assertIsNotNone(match, "lang assignment not found")
        self.assertEqual(match.group(1), "en")

    def test_lang_inside_sentinel_block(self):
        """Lang injection must be inside the __forgeKeysRegistered sentinel to avoid
        running on every Streamlit rerun."""
        sentinel_pos = self.src.find("__forgeKeysRegistered")
        lang_pos     = self.src.find("documentElement.lang")
        self.assertGreater(
            lang_pos, sentinel_pos,
            "lang injection should appear after the sentinel flag check",
        )

    def test_sr_only_css_injected_globally(self):
        """.sr-only CSS class must be injected in app.py for all panels to use."""
        self.assertIn(
            ".sr-only", self.src,
            "Global .sr-only CSS not found in app.py",
        )


# ===========================================================================
# Runner
# ===========================================================================

if __name__ == "__main__":
    unittest.main()
